---
title: "04_Analisis"
author: "Pao"
date: "11/11/2019"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(data.table)
library(metR)
library(reticulate)

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")

geom_mapa <- function() {
  geom_sf(data = map, fill = NA, color = "black", size = 0.2, inherit.aes = FALSE)
}

# coord <- ReadNetCDF("analysis.ensmean", 
#                     vars = c(lon = "XLONG", lat = "XLAT")) %>% 
#   .[, Time := NULL]

# ReadNetCDF("E3/ANA/20181122060000/analysis.ensmean", vars = c("P", "PB")) %>% 
#   .[, P := (P + PB)/100] %>% 
#   .[P %between% c(898, 902)] %>% 
#   .[] %>% 
#   ggplot(aes(bottom_top)) +
#   geom_density()
```

# Análisis 

Quermeos comparar los experimentos E3 que asimila el prepbufr nivel 3 (oficiales + automáticas) y el E4 que solo asimila prepbufr nivel 1. Por ahora nos vamos a concentrar en la media del aálisis.

## CAPE y CIN

```{r read, include=FALSE}
files <- list.files("analisis/mucape", full.names = TRUE)

cape <- lapply(files, function(file) {
  details <- unglue::unglue(file, "analisis/mucape/mcape_ana_{exp}_{date}.nc")[[1]]
  
  ReadNetCDF(file, vars = c(value = "cape_2d")) %>% 
    .[, `:=`(exp = details$exp, 
             date = lubridate::ymd_hms(details$date))] %>%
    setnames(old = "mcape_mcin_lcl_lfc", new = "variable") %>% 
    .[]
}) %>% 
  rbindlist() %>% 
  .[variable == "mcape"]

coord <- ReadNetCDF(files[1], vars = c(lon = "XLONG")) %>% 
  .[, lat := ReadNetCDF(files[1], vars = c(lat = "XLAT"))$lat]

```

  
```{r}
south_north_band <- c(105, 109)

cape %>% 
  .[south_north %between% south_north_band, .(mean_cape = mean(value, na.rm = TRUE)), by = .(date, west_east, exp)] %>%
  # dcast(date + west_east ~ exp, value.var = "mean_cape") %>% 
  .[coord[south_north %~% mean(south_north_band)], on = .NATURAL] %>% 
  ggplot(aes(lon, date)) +
  geom_contour_fill(aes(z = mean_cape), breaks = seq(500, 4000, 500), na.fill = 0) +
  geom_contour2(data = function(d) dcast(d, date + lon ~ exp, value.var = "mean_cape")[, dif := E3 - E4],
    aes(z = dif), breaks = seq(500, 4000, 500), na.fill = 0) +
  scale_fill_distiller(name = NULL, palette = "YlOrRd", direction = 1, 
                       breaks = seq(500, 4000, 500),
                       guide = guide_colorstrip(barwidth = 40,
                                                barheight = 0.8)) +
  labs(title = "MCAPE",
       subtitle = "at 32ºS") +
  scale_x_longitude(ticks = 2.5, expand = c(0,0)) +
  scale_y_datetime("Time", date_labels = "%b-%d", expand = c(0,0)) +
  facet_wrap(~exp, labeller = labeller(exp = c(E3 = "CONV+AUT", E4 = "CONV")), ncol = 1) +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom", 
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3)) 

ggsave("fig/cape_hov.png", dpi = 150, width = unit(10, "cm"), height = unit(18, "cm"))
```


```{r}

interpol <- function(x, y, z, ...) {
  IL <- interp::interp(x, y, z, ...)
  CJ(y = IL$y, x = IL$x)[, z := c(IL$z)] 
}

cape[date %in% ymd_h(c("2018-11-22 00",
                       #"2018-11-22 03", 
                       "2018-11-22 06"))] %>% 
  .[coord, on = .NATURAL] %>% 
  .[!is.finite(value), value := 0] %>% 
  .[, interpol(lon, lat, value, nx = 50, ny = 50), by = .(date, exp)] %>% 
  setnames(c("x", "y", "z"), c("lon", "lat", "value")) %>%
  na.omit() %>% 
  .[, date := factor(date)] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = round(value, 6)), na.fill = 0) +
  # geom_contour2(data = function(d) dcast(d, lat + lon + date ~ exp, value.var = "value")[, dif := E3 - E4],
  #   aes(z = dif), bins = 5)+
  geom_mapa() +
  scale_fill_distiller(name = NULL, palette = "YlOrRd", direction = 1, 
                       # breaks = seq(500, 5000, 500),
                       guide = guide_colorstrip(barwidth = 30,
                                                barheight = 0.8)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_grid(exp ~ date, labeller = labeller(exp = c(E3 = "CONV+AUT", E4 = "CONV"))) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  labs(title = "MCAPE",
       x = "Longitude",
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom", 
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3)) 

ggsave("fig/cape_esp.png", dpi = 150, width = unit(15, "cm"), height = unit(15, "cm"))
```



## Temperatura y humedad

Perfiles de temperatura y humedad promediados en todo el dominio

```{r}
perfil_E3 <- fread("analisis/perfil_T_Q_ana_E3.csv") %>% 
  .[, date := ymd_hms(date)] 

perfil_lev_E3 <- fread("analisis/perfil_lev_T_Q_ana_E3.csv") %>% 
  .[, date := ymd_hms(date)] 

perfil_E4 <- fread("analisis/perfil_T_Q_ana_E4.csv") %>% 
  .[, date := ymd_hms(date)]

perfil_lev_E4 <- fread("analisis/perfil_lev_T_Q_ana_E4.csv") %>% 
  .[, date := ymd_hms(date)] 

perfil_lev_E4[perfil_lev_E3, on = c("lev", "date")] %>%
  .[] %>% 
  .[, `:=`(diff_T = i.T - T,
           diff_Q = i.QVAPOR - QVAPOR)] %>% 
  ggplot(aes(date, lev)) +
  geom_contour_fill(aes(z = diff_T), breaks = seq(-1, 1, 0.2)) +
  scale_fill_divergent(name = NULL,
                       breaks = seq(-1, 1, 0.2),
                       guide = guide_colorstrip(inside = TRUE,
                                                barwidth = 35,
                                                barheight = 0.8)) +
  labs(title = "Temperature difference (K)",
       subtitle = "CONV+AUT - CONV",
       x = "Time",
       y = "Pressure level") +
  scale_y_level(name = "Pressure level", breaks = c(1000, 850, 750, 500, 300, 200, 100)) +
  scale_x_datetime(expand = c(0,0), date_labels = "%HZ \n %b-%d", date_breaks = "12 hours") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

ggsave("fig/temperature_diff.png", dpi = 150, width = unit(12, "cm"), height = unit(10, "cm"))

perfil_lev_E4[perfil_lev_E3, on = c("lev", "date")] %>%
  .[] %>% 
  .[, `:=`(diff_T = i.T - T,
           diff_Q = i.QVAPOR - QVAPOR)] %>% 
  ggplot(aes(date, lev)) +
  geom_contour_fill(aes(z = diff_Q*1000), breaks = seq(-0.0004, 0.0016, 0.0002)*1000) +
  scale_fill_divergent(name = NULL,
                       breaks = seq(-0.0004, 0.0016, 0.0002)*1000,
                       guide = guide_colorstrip(inside = TRUE,
                                                barwidth = 35,
                                                barheight = 0.8)) +

  scale_y_level(name = "Pressure level", breaks = c(1000, 850, 750, 500, 300, 200, 100)) +
  scale_x_datetime(expand = c(0,0), date_labels = "%HZ \n %b-%d", date_breaks = "12 hours") +
  labs(title = "Humidity difference (g/Kg)",
       subtitle = "CONV+AUT - CONV",
       y = "Pressure level",
       x = "Time") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

ggsave("fig/humidity_diff.png", dpi = 150, width = unit(12, "cm"), height = unit(10, "cm"))
```

## Circulación

```{r}
fcsts <- expand_grid(fcsts = c("20181121210000", "20181122000000", "20181122030000", "20181122060000"),
                     exp = c("E3", "E4"))

temp_spd <- lapply(seq_len(nrow(fcsts)), function(f) {
  
  tmp <- ReadNetCDF(paste0("analisis/u_", fcsts[f, 1], "_", fcsts[f, 2], ".nc"), vars = c(u = "uvmet")) %>% 
    .[, v := ReadNetCDF(paste0("analisis/v_", fcsts[f, 1], "_", fcsts[f, 2], ".nc"), vars = c(v = "uvmet"), out = "vector")] %>% 
    .[, t := ReadNetCDF(paste0("analisis/t_", fcsts[f, 1], "_", fcsts[f, 2], ".nc"),  vars = c(t = "temp"), out = "vector")] %>% 
    .[, date :=  ymd_hms(fcsts[f, 1])] %>% 
    .[, exp := fcsts[f, 2]] %>%  
    .[]
}) %>% 
  rbindlist()

mean_temp_spd <- temp_spd[bottom_top <= 7, .(t = mean(t), u = u[bottom_top == 1], v = v[bottom_top == 1]), 
         by = .(south_north, west_east, date, exp)] %>% 
  .[coord, on = c("south_north", "west_east")] %>% 
  .[, date := factor(date)]

diff_temp_spd <- copy(mean_temp_spd) %>% 
  melt(id.vars = c("lon", "lat", "date", "exp"), measure.vars = c("t", "u", "v")) %>% 
  dcast(lon + lat + date + variable ~ exp, value.var = "value") %>% 
  .[, diff := E3 - E4]
```


```{r}
mean_temp_spd %>% 
  # .[t > 278] %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = t - 273)) +
  scale_color_viridis_c(name = NULL,
                        option = "B" ,
                        breaks = seq(5, 35, 5),
                        limits = c(10, 35),
                        oob = scales::squish,
                        guide = guide_colorstrip(inside = FALSE,
                                                barwidth = 30,
                                                barheight = 0.8)) +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA, color = "black", size = 0.2) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  geom_vector(aes(dx = u, dy = v), data = function(x) x[is.cross(south_north, west_east, 4)]) +
  scale_mag() +
  facet_grid(exp ~ date, labeller = labeller(exp = c(E3 = "CONV+AUT", E4 = "CONV"))) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "Low level temperature",
       x = "Longituted",
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

ggsave("fig/campo_temperatura.png", dpi = 150, width = unit(30, "cm"), height = unit(15, "cm"))

library(patchwork)
mean_temp_spd %>% 
  .[exp == "E3" & date %in% c("2018-11-22 00:00:00", "2018-11-22 06:00:00")] %>% 
  .[] %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = t - 273)) +
  scale_color_viridis_c(name = NULL,
                        option = "B" ,
                        breaks = seq(5, 35, 5),
                        limits = c(10, 35),
                        oob = scales::squish,
                        guide = guide_colorstrip(inside = FALSE,
                                                barwidth = 0.8,
                                                barheight = 20)) +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA, color = "black", size = 0.2) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  geom_vector(aes(dx = u, dy = v), data = function(x) x[is.cross(south_north, west_east, 4)]) +
  scale_mag() +
  facet_grid(exp ~ date, labeller = labeller(exp = c(E3 = "CONV+AUT", E4 = "CONV"))) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "CONV+AUT",
       x = NULL,
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3),
        strip.background = element_blank(),
        strip.text.y = element_blank()) +

diff_temp_spd %>% 
  dcast(lon + lat + date ~variable, value.var = "diff") %>% 
  .[date %in% c("2018-11-22 00:00:00", "2018-11-22 06:00:00")] %>% 
  .[coord, on = .NATURAL] %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = t)) +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA, color = "black", size = 0.2) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  geom_vector(aes(dx = u, dy = v), data = function(x) x[is.cross(south_north, west_east, 4)]) +
  scale_mag() +
  scale_color_divergent(name = NULL,
                        breaks = seq(-7, 8, 2),
                        guide = guide_colorstrip(inside = FALSE,
                                                barwidth = 0.8,
                                                barheight = 20)) +
  facet_grid(. ~ date) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "CONV+AUT - CONV",
       x = "Longituted",
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  plot_layout(ncol = 1)

ggsave("fig/campo_temperatura_diff.png", dpi = 150, width = unit(15, "cm"), height = unit(15, "cm"))
```

## Humedad en niveles bajos

```{r}


q <- lapply(seq_len(nrow(fcsts)), function(f) {
  
  tmp <- ReadNetCDF(paste0("analisis/q_", fcsts[f, 1], "_", fcsts[f, 2], ".nc"), vars = c(q = "QVAPOR")) %>% 
    .[, date :=  ymd_hms(fcsts[f, 1])] %>% 
    .[, exp := fcsts[f, 2]] %>%  
    .[]
}) %>% 
  rbindlist()

q[bottom_top <= 7, .(q = mean(q)), by = .(south_north, west_east, date, exp)] %>% 
  .[coord, on = c("south_north", "west_east")] %>% 
  .[, date := factor(date)] %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = q*1000)) +
  scale_color_distiller(name = NULL,
                        palette = "BrBG", direction = 1,
                        breaks = seq(0, 0.02, 0.002)*1000,
                        guide = guide_colorstrip(inside = FALSE,
                                                barwidth = 40,
                                                barheight = 0.8)) +
  geom_sf(data = map, inherit.aes = FALSE, color = "black", fill = NA, size = 0.2) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  facet_grid(exp ~ date, labeller = labeller(exp = c(E3 = "CONV+AUT", E4 = "CONV"))) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "Low level humidity (g/Kg)",
       x = "Longituted",
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

ggsave("fig/campo_humedad.png", dpi = 150, width = unit(30, "cm"), height = unit(15, "cm"))


```
```{r}
q[bottom_top <= 7, .(q = mean(q)), by = .(south_north, west_east, date, exp)] %>% 
  .[coord, on = c("south_north", "west_east")] %>% 
  .[, date := factor(date)] %>% 
  .[exp == "E3" & date %in% c("2018-11-22 00:00:00", "2018-11-22 06:00:00")] %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = q*1000)) +
  scale_color_distiller(name = NULL,
                        palette = "BrBG", direction = 1,
                        breaks = seq(0, 0.02, 0.002)*1000,
                        guide = guide_colorstrip(inside = FALSE,
                                                barwidth = 0.8,
                                                barheight = 20)) +
  geom_sf(data = map, inherit.aes = FALSE, color = "black", fill = NA, size = 0.2) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  facet_grid(exp ~ date) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "CONV+AUT",
       x = NULL,
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3),
        strip.background = element_blank(),
        strip.text.y = element_blank()) +

q[bottom_top <= 7, .(q = mean(q)), by = .(south_north, west_east, date, exp)] %>% 
  .[coord, on = c("south_north", "west_east")] %>% 
  .[, date := factor(date)] %>% 
  dcast(lon + lat + date ~ exp, value.var = "q") %>% 
  .[, diff := E3 - E4] %>% 
  .[date %in% c("2018-11-22 00:00:00", "2018-11-22 06:00:00")] %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = diff*1000)) +
  scale_color_divergent(name = NULL,
                        breaks = seq(-6, 10, 2),
                        guide = guide_colorstrip(inside = FALSE,
                                                barwidth = 0.8,
                                                barheight = 20)) +
  geom_sf(data = map, inherit.aes = FALSE, color = "black", fill = NA, size = 0.2) +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  facet_grid(. ~ date) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "CONV+AUT - CONV",
       x = "Longituted",
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  plot_layout(ncol = 1)

ggsave("fig/campo_humedad_diff.png", dpi = 150, width = unit(14, "cm"), height = unit(15, "cm"))
```

