---
title: "05_Pronósticos"
author: "Pao"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(data.table)
library(metR)
library(aiRthermo)
library(reticulate)

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")

coord <- ReadNetCDF("E3/ANA/20181122060000/analysis.ensmean", vars = c(lon = "XLONG", lat = "XLAT")) %>% 
  .[, Time := NULL]

# ReadNetCDF("E3/ANA/20181122060000/analysis.ensmean", vars = c("P", "PB")) %>% 
#   .[, P := (P + PB)/100] %>% 
#   .[P %between% c(898, 902)] %>% 
#   .[] %>% 
#   ggplot(aes(bottom_top)) +
#   geom_density()
```

# Pronósticos

Los pronósticos fueron inicializados a partir de la media del análisis a las:

* 21Z del 21/11
* 00Z del 22/11
* 03Z del 22/11
* 06Z del 22/11

Se usaron las parametrizaciones YSU y KF y todos los pronósticos corrieron hasta las 12Z del 23/11.

## "Validación con datos de precipitación IMERG

```{r}
files <- Sys.glob("../IMERG_20181122/*")

pp_imerg <- lapply(files, function(f) {
  date <- str_extract(f, "\\d{8}")
  start <- str_extract(str_extract(f, "S\\d{6}"), "\\d{6}")
  end <- str_extract(str_extract(f, "E\\d{6}"), "\\d{6}")
  
  pp <- ReadNetCDF(f, vars = c(pp = "Grid/precipitationCal"), subset = list("Grid/lon" = -80:-50, 
                                                                       "Grid/lat" = -45:-15)) %>% 
    .[, start_date := ymd_hms(paste(date, start))] %>% 
    .[, end_date := ymd_hms(paste(date, end))] %>% 
    .[]
}) %>% 
  rbindlist() %>% 
  setnames(c("Grid/lon", "Grid/lat"), c("lon", "lat"))
```

```{r}
fcsts <- expand_grid(fcsts = c("20181121210000", "20181122000000", "20181122030000", "20181122060000"),
                        exp = c("E3", "E4"))

pp <- lapply(seq_len(nrow(fcsts)), function(f) {
  
  tmp <- ReadNetCDF(paste0("analisis/pp_acum_", fcsts[f, 2], "_fcst", fcsts[f, 1], ".nc"), vars = c(pp = "__xarray_dataarray_variable__",
                                                                                                    lon = "XLONG",
                                                                                                    lat = "XLAT")) %>% 
  .[, init_date :=  ymd_hms(fcsts[f, 1])] %>% 
  .[, exp := fcsts[f, 2]] %>%  
  .[]
}) %>% 
  rbindlist()
```

```{r}
pp_imerg[start_date %between% c(as_datetime("2018-11-22 06:00:00"), as_datetime("2018-11-23 11:30:00")), 
                    .(pp = sum(pp)), by = .(lon, lat)] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = pp), breaks = seq(0, 360, 50)) +
  # geom_point(aes(color = pp), breaks = seq(50, 360, 50)) +
  scale_fill_gradient(low  = "white", high = "navy",
                       # limits = c(0, 350),
                       oob = scales::squish,
                       breaks = seq(0, 360, 50)) +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA, size = 0.2) +
  coord_sf(ylim = c(-41, -20), xlim = c(-75, -52.5)) +
  theme_minimal() +
  labs("Cumulado entre las 06 del 22 y las 00 del 22. FALTA acumular 23!")

pp[, init_date := factor(init_date)] %>% 
  ggplot(aes(lon, lat)) +
  # geom_contour_fill(aes(z = pp), breaks = seq(0, 360, 50)) +
  geom_point(aes(color = pp), breaks = seq(50, 360, 50)) +
  scale_color_gradient(low  = "white", high = "navy",
                       # limits = c(0, 350),
                       oob = scales::squish,
                       breaks = seq(0, 360, 50)) +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA, size = 0.2) +
  coord_sf(ylim = c(-41, -20), xlim = c(-75, -52.5)) +
  facet_grid(exp ~ init_date) +
  theme_minimal() +
  labs("Cumulado entre las 06 del 22 y las 06 del 23")
```
 
 
```{r}
pp_hr <- copy(pp_imerg)[, `:=`(hora = hour(start_date),
                                dia = day(start_date))] %>% 
  .[start_date %between% c(as_datetime("2018-11-22 06:00:00"), as_datetime("2018-11-23 11:30:00")), 
                    .(pp = sum(pp)), by = .(hora, dia, lon, lat)] %>% 
  .[lat %between% c(-34, -30), .(pp = mean(pp)), by = .(hora, dia, lon)] %>% 
  .[, time := make_datetime(2018, 11, dia, hora)]

pp_hr %>% 
  ggplot(aes(lon, time)) +
  geom_contour_fill(aes(z = pp), breaks = seq(1, 20, 3)) +
  # geom_point(aes(color = pp), breaks = seq(0, 20, 5)) +
  scale_fill_gradient(low  = "white", high = "navy",
                       # limits = c(0, 350),
                       oob = scales::squish,
                       breaks = seq(1, 20, 3)) +
  theme_minimal() +
  metR:::theme_field()
```
 
