---
title: "05_Pronósticos"
author: "Pao"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(data.table)
library(metR)
library(reticulate)

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")

coord <- ReadNetCDF("analisis/mucape/mcape_ana_E3_20181120180000.nc", vars = c(lon = "XLONG")) %>% 
  .[, lat := ReadNetCDF("analisis/mucape/mcape_ana_E3_20181120180000.nc", vars = c(lat = "XLAT"))$lat]

geom_mapa <- function() {
  geom_sf(data = map, fill = NA, color = "black", size = 0.2, inherit.aes = FALSE)
}

exp <- c(E3 = "CONV+AUT",
         E4 = "CONV",
         E5 = "AUT",
         E6 = "SATWND")

init_fcst = c("2018-11-22 00:00:00" = "Init time = 00Z",
              "2018-11-22 06:00:00" = "Init time = 06Z")


# ReadNetCDF("E3/ANA/20181122060000/analysis.ensmean", vars = c("P", "PB")) %>% 
#   .[, P := (P + PB)/100] %>% 
#   .[P %between% c(898, 902)] %>% 
#   .[] %>% 
#   ggplot(aes(bottom_top)) +
#   geom_density()
```

# Pronósticos

Los pronósticos fueron inicializados a partir de la media del análisis a las:

* 21Z del 21/11
* 00Z del 22/11
* 03Z del 22/11
* 06Z del 22/11

Se usaron las parametrizaciones YSU y KF y todos los pronósticos corrieron hasta las 12Z del 23/11.

## "Validación con datos de precipitación IMERG

```{r}
files <- Sys.glob("../datosmunin2/IMERG_20181122/*")

pp_imerg <- lapply(files, function(f) {
  date <- str_extract(str_extract(f, "\\d{8}-"), "\\d{8}")
  start <- str_extract(str_extract(f, "S\\d{6}"), "\\d{6}")
  end <- str_extract(str_extract(f, "E\\d{6}"), "\\d{6}")
  
  pp <- ReadNetCDF(f, vars = c(pp = "Grid/precipitationCal"), subset = list("Grid/lon" = -80:-50, 
                                                                            "Grid/lat" = -45:-15)) %>% 
    .[, start_date := ymd_hms(paste(date, start))] %>% 
    .[, end_date := ymd_hms(paste(date, end))] %>% 
    .[]
}) %>% 
  rbindlist() %>% 
  setnames(c("Grid/lon", "Grid/lat"), c("lon", "lat"))

pp_imerg_acum <- pp_imerg[start_date %between% c(as_datetime("2018-11-22 06:00:00"), as_datetime("2018-11-23 11:30:00")), 
                          .(pp = sum(pp)), by = .(lon, lat)]
```

```{r}
# fcsts <- expand_grid(fcsts = c("20181121210000", "20181122000000", "20181122030000", "20181122060000"),
fcsts <- expand_grid(fcsts = c("20181122000000", "20181122060000"),                     
                     exp = c("E4", "E5", "E6"))

pp <- lapply(seq_len(nrow(fcsts)), function(f) {
  
  tmp <- ReadNetCDF(paste0("analisis/pp_acum_", fcsts[f, 2], "_fcst", fcsts[f, 1], ".nc"), vars = c(pp = "__xarray_dataarray_variable__",
                                                                                                    lon = "XLONG",
                                                                                                    lat = "XLAT")) %>% 
    .[, init_date :=  ymd_hms(fcsts[f, 1])] %>% 
    .[, exp := fcsts[f, 2]] %>%  
    .[]
}) %>% 
  rbindlist()

pp_inter <- pp[, interp::interp(lon, lat, pp, output = "points", xo = pp_imerg_acum$lon, yo = pp_imerg_acum$lat), 
               by = .(init_date, exp)] %>% 
  setnames(c("x", "y", "z"), c("lon", "lat", "pp"))
```

```{r}
pp_imerg_acum %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = pp), breaks = seq(0, 360, 50)) +
  # geom_point(aes(color = pp), breaks = seq(50, 360, 50)) +
  scale_fill_gradient(low  = "white", high = "navy",
                      # limits = c(0, 350),
                      oob = scales::squish,
                      breaks = seq(0, 360, 50)) +
  geom_sf(data = map, inherit.aes = FALSE, color = "black", fill = NA, size = 0.2) +
  coord_sf(ylim = c(-41, -20), xlim = c(-75, -52.5)) +
  theme_minimal() +
  labs(title = "Cumulado entre las 06 del 22 y las 12 del 23")

pp_inter %>% 
  .[, init_date := factor(init_date)] %>% 
  # .[init_date == unique(init_date)[2] | init_date == unique(init_date)[4]] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = pp), breaks = seq(10, 300, 50), na.fill = 0) +
  scale_fill_gradient("FCST", low  = "white", high = "black",
                       # limits = c(0, 350),
                       oob = scales::squish,
                       breaks = seq(0, 300, 50),
                       guide = guide_colorstrip(barwidth = 20,
                                                barheight = 0.7)) +
  geom_contour(data = pp_imerg_acum, aes(z = pp, color = ..level..), 
               breaks = seq(0, 300, 50),
               size = 1) +
  scale_color_viridis_c("IMERG", direction = -1,
                        breaks = seq(0, 300, 50),
                        guide = guide_colorstrip(inside = TRUE,
                                                 barwidth = 20,
                                                barheight = 0.8)) +
  geom_mapa() +
  coord_sf(xlim = range(coord$lon), ylim = range(coord$lat)) +
  facet_grid(exp ~ init_date, labeller = labeller(exp = exp,
                                                  init_date = init_fcst)) +
  labs(title = "Accumulated precipitation",
       subtitle = "11/22 06Z to 11/23 12Z",
       x = "Longitude",
       y = "Latitude") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom",
        panel.grid = element_line(linetype = 3))

ggsave("fig/pp_acum.png", dpi = 200, width = unit(15, "cm"), height = unit(30, "cm"))
```


```{r}
pp_imerg_hr <- copy(pp_imerg)[, `:=`(hora = hour(start_date),
                               dia = day(start_date))] %>% 
  .[start_date %between% c(as_datetime("2018-11-22 06:00:00"), as_datetime("2018-11-23 11:30:00")), 
    .(pp = sum(pp)), by = .(hora, dia, lon, lat)] %>% 
  .[lat %between% c(-34, -30), .(pp = mean(pp)), by = .(hora, dia, lon)] %>% 
  .[, date := make_datetime(2018, 11, dia, hora)] 

fcsts <- expand_grid(fcsts = c("20181122000000", "20181122060000"),
                     exp = c("E4", "E5", "E6"))

pp_hov <- lapply(seq_len(nrow(fcsts)), function(f) {
  
  tmp <- fread(paste0("analisis/pp_hov_fcst", fcsts[f, 1], "_", fcsts[f, 2], ".csv")) %>%
    # .[, pp := pp - pp[date == "2018-11-22T06:00:00Z"]] %>%
    .[, pp_10 := c(NA, diff(pp)), by = .(west_east, fcst, exp)] %>% 
    .[date %between% c("2018-11-22T06:00:00Z", "2018-11-23T12:00:00Z")] %>% 
    .[, date := ymd_hms(date)] %>% 
    .[, fcst := ymd_hms(fcst)] %>% 
    .[]
}) %>% 
  rbindlist()

pp_hov_acum <- copy(pp_hov)[, `:=`(hora = hour(date),
                               dia = day(date))] %>% 
  .[, .(pp = sum(pp_10)), by = .(hora, dia, west_east, fcst, exp)] %>% 
  .[, date := make_datetime(2018, 11, dia, hora)]

pp_hov_acum[coord[south_north == 120, .(west_east, lon)], on = c("west_east")] %>% 
  .[, fcst := factor(fcst)] %>% 
  # .[fcst == unique(fcst)[2] | fcst == unique(fcst)[4]] %>% 
  ggplot(aes(lon, date)) +
  geom_contour_fill(aes(z = round(pp, 6)), breaks = seq(0, 15, 1), na.fill = 0) +
  scale_fill_gradient("FCST", low  = "white", high = "black",
                       # limits = c(0, 350),
                       oob = scales::squish,
                       breaks = seq(0, 15, 3),
                       guide = guide_colorstrip(barwidth = 20,
                                                barheight = 0.7)) +
  geom_contour(data = pp_imerg_hr, aes(z = pp, color = ..level..), 
               breaks = seq(0, 20, 3),
               size = 1) +
  scale_color_viridis_c("IMERG", direction = -1,
                        breaks = seq(0, 20, 3),
                        guide = guide_colorstrip(inside = TRUE,
                                                 barwidth = 20,
                                                barheight = 0.8)) +
  facet_grid(exp ~ fcst, labeller = labeller(exp = exp,
                                             fcst = init_fcst)) +
  scale_x_longitude(breaks = seq(-75, -55, 5), expand = c(0,0)) +
  scale_y_datetime(date_breaks = "6 hours", date_labels = "%b-%d %HZ") +
  labs(title = "Hovmöller of accumulated precipitation",
    subtitle = "34ºS to 30ºS latitud",
    x = "Longitud",
    y = "Time") +
  theme_minimal(base_size = 26) +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

ggsave("fig/pp_hov.png", dpi = 200, width = unit(15, "cm"), height = unit(22, "cm"))
```

```{r}

pp_imerg_hr %>% 
  ggplot(aes(lon, date)) +
  geom_contour_fill(aes(z = pp), breaks = seq(1, 20, 3)) +
  # geom_point(aes(color = pp), breaks = seq(0, 20, 5)) +
  scale_fill_gradient(low  = "white", high = "navy",
                      # limits = c(0, 350),
                      oob = scales::squish,
                      breaks = seq(1, 20, 3)) +
  theme_minimal() +
  metR:::theme_field()
```

