---
onin
title: "Entrenamiento de coeficientes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(metR)
library(data.table)
library(lubridate)
library(scattermore)
library(patchwork)
library(unglue)
source("help_functions.R")
source("postprocesamiento.R")
source("goes_functions.R")

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")

geom_mapa <- function() {
  list(geom_sf(data = map, fill = NA, color = "black", size = 0.2, inherit.aes = FALSE),
       coord_sf(xlim = c(-78, -50), ylim = c(-42, -19)))
}

map_proj <- "+proj=lcc +lat_1=-30.9659996032715 +lat_2=-30.9659996032715 +lat_0=-30.9660034179688 +lon_0=-63.5670013427734 +a=6370000 +b=6370000"

coord <- ReadNetCDF("analisis/q_20181121210000_E3.nc", vars = c(lon = "XLONG")) %>%
  .[, lat := ReadNetCDF("analisis/q_20181121210000_E3.nc", vars = c(lat = "XLAT"))$lat]
```

## Entrenamiento de coeficientes

```{r}
files <- list.files("/home/paola.corrales/datosmunin/EXP/E7/ANA/training/",
                    pattern = "satbias_2", 
                    recursive = TRUE,
                    full.names = TRUE)

satbias <- map(files, function(f){
  meta <- unglue::unglue(basename(f), "satbias_{date}")
  read_satbias(f) %>% 
    as.data.table() %>% 
    .[, ":="(date = ymd_hms(meta[[1]][["date"]]))]
  
}) %>% 
  rbindlist()

sensores <- c("amsua_n15",
              "amsua_n18",
              "amsua_n19",
              # "amsua_metop_a",
              "amsua_metop-b",
              "amsua_aqua",
              "airs_aqua",
              "iasi_metop-a",
              "iasi_metop-b", 
              "hirs4_n19",
              "hirs4_metop-a",
              "hirs4_metop-b",
              "mhs_metop-a",
              "mhs_metop-b",
              "mhs_n18",
              "mhs_n19",
              "mhs_metop-a",
              "atms_npp",
              "atms_n20",
              "cris-fsr_npp",
              "cris-fsr_n20"
)

satbias <- satbias[sensor %in% sensores]

satinfo <- fread("satinfo.txt") %>% 
  setnames(c("!sensor/instr/sat", "chan"), c("sensor", "channel"))

satbias <- satinfo[satbias, on = c("sensor", "channel")]
```

```{r eval=FALSE}
# satbias[sensor %in% sensores[1] & iuse == 1] %>% 
#   melt(measure.vars = paste0("coeff", c(1, 3:5, 8))) %>% 
#   ggplot(aes(date, value)) +
#   geom_point(aes(group = channel), size= 0.5) +
#   geom_path(aes(group = channel), size= 0.5) +
#   scale_x_datetime(date_labels = "%d") +
#   labs(title = paste("Coefficientes for", sensores[1]),
#        subtitle = "Channel 4") +
#   facet_grid(channel~variable, scales = "free_y", 
#              labeller = labeller(variable = c("coeff1" = "Offset",
#                                               "coeff3" = "CLW",
#                                               "coeff4" = "TLR^2",
#                                               "coeff5" = "TLR",
#                                               "coeff8" = "Emiss"))) +
#   theme_minimal() 


for (this_sensor in sensores){
  print(this_sensor)
  g <- satbias[sensor %in% this_sensor & iuse == 1] %>% 
    melt(measure.vars = paste0("coeff", c(1, 3:5, 8))) %>% 
    ggplot(aes(date, value)) +
    geom_point(aes(color = variable), size= 0.5) +
    geom_path(aes(color = variable), size= 0.5) +
    scale_color_brewer(type = "qual", palette = "Dark2",
                       labels = c("coeff1" = "Offset",
                                  "coeff3" = "CLW",
                                  "coeff4" = "TLR^2",
                                  "coeff5" = "TLR",
                                  "coeff8" = "Emiss")) +
    scale_x_datetime(date_labels = "%d") +
    labs(title = paste("Coefficientes for", this_sensor),
         color = "") +
    facet_wrap(~channel, scales = "free_y", ncol = 5) +
    theme_minimal() +
    theme(legend.position = "bottom")
  
  rows <- satbias[sensor %in% this_sensor & iuse == 1, channel] %>% 
    unique(by = channel) %>% 
    length() / 5
  
  h <- ceiling(ceiling(rows)*700/300)
  if (h > 0){
    
    ggsave(paste0(this_sensor, ".png"), plot = g, width = 9, height = h, limitsize = FALSE)
  }
}




```

## Evaluaci贸n del ensamble

```{r}
# library(foreach)
# library(doParallel)
# 
# myCluster <- makeCluster(10)
# registerDoParallel(myCluster)

files <- list.files("/home/paola.corrales/datosmunin/EXP/E7/ANA/training/NPP/", 
                    full.names = TRUE)
var_nc <- "T"

# out <- foreach(f = 1:length(files),
#                .packages = c("data.table", "metR", "lubridate", "dplyr", "unglue"),
#                .export = c("files", "var_nc"),
#                .combine = "rbind") %dopar% {
out <- purrr::map(files, function(f) {
  print(basename(f))
  meta <- unglue(basename(f), "NPP_{date}_AN.nc")
  
  nc_file <- ReadNetCDF(f, vars = c("XLONG", "XLAT", var_nc),
                        subset = list(lat = 5:235, lon = 5:195)) %>% 
    .[, .(mean = mean(T, na.rm = TRUE)), by = .(lev, ens)] %>% 
    .[, .(mean = mean(mean, na.rm = TRUE),
          sd = sd(mean, na.rm = TRUE)), by = .(lev)] %>% 
    .[, date := ymd_h(meta[[1]][[1]])]
}) %>% 
  rbindlist()
#                }
# 
# stopCluster(myCluster)

fwrite(out, paste0("analisis/", var_nc, ".csv"))

```

```{r}
fread("analisis/T.csv") %>% 
  .[, date := ymd_hms(date)] %>% 
  ggplot(aes(date, lev)) +
  geom_contour_fill(aes(z = sd), breaks = seq(0, 0.4, 0.05)) +
  scale_fill_viridis_c(option = "A", guide = guide_colorstrip(barheight = 15),
                       breaks = seq(0.1, 0.4, 0.05), limits = c(0.1, NA)) +
  scale_y_level() +
  scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d") +
  labs(fill = "SPREAD",
       title = "Temperatura",
       x = "") +
  theme_minimal()

fread("analisis/Q.csv") %>% 
  .[, date := ymd_hms(date)] %>% 
  ggplot(aes(date, lev)) +
  geom_contour_fill(aes(z = sd), breaks = seq(0, 0.4, 0.05)) +
  scale_fill_viridis_c(option = "A", guide = guide_colorstrip(barheight = 15),
                       breaks = seq(0, 0.3, 0.05), limits = c(0, NA)) +
  scale_y_level() +
  scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d") +
  labs(fill = "SPREAD",
       title = "Humedad",
       x = "") +
  theme_minimal()
```

## Evaluaci贸n de casos particulares

```{r}
fisica <- data.table(ens = 1:60, 
                     fisica = rep(c("KF-YSU", 
                                    "BMJ-YSU",
                                    "GF-YSU",
                                    "KF-MYJ",
                                    "BMJ-MYJ",
                                    "GF-MYJ",
                                    "KF-MYNN2",
                                    "BMJ-MYNN2",
                                    "GF-MYNN2"), length.out = 60)) %>% setDT()

ana <- ReadNetCDF("/home/paola.corrales/datosmunin/EXP/E7/ANA/week1/NPP/NPP_2018-11-13_01_AN.nc", vars = c("XLONG", "XLAT", "MDBZ")) %>%
  fisica[., on = .NATURAL] %>%
  .[, c("x", "y") := wrf_project(XLONG, XLAT)]

ana <- ReadNetCDF("/home/paola.corrales/datosmunin/EXP/E7/ANA/week2/NPP/NPP_2018-11-13_01_AN.nc", vars = c("XLONG", "XLAT", "MDBZ")) %>%
  fisica[., on = .NATURAL] %>%
  .[, c("x", "y") := wrf_project(XLONG, XLAT)]

ana[, .(mean = mean(MDBZ, na.rm = TRUE),
        sd = sd(MDBZ, na.rm = TRUE)), by = .( XLONG, XLAT)] %>% 
  ggplot(aes(XLONG, XLAT)) +
  geom_point(aes(color = sd)) +
  scale_color_viridis_c(option = "A") +
  geom_mapa() +
  # facet_wrap(~lev) +
  theme_minimal()


positive_breaks <- function (binwidth = NULL, bins = 10, exclude = NULL) 
{
  function(range, binwidth2) {
    if (!is.null(binwidth)) 
      binwidth2 <- binwidth
    if (is.null(binwidth2)) {
      b <- pretty(range, bins)
      b <- b[b > 0]
      return(b[!(b %in% exclude)])
    }
    else {
      b <- scales::fullseq(range, binwidth2)
      b <- b[b > 0]
      b[!(b %in% exclude)]
    }
  }
}


ana[, .(MDBZ = mean(MDBZ, na.rm = TRUE)), by = .(fisica, x, y)] %>% 
  # ana %>%
  # .[MDBZ > 10 & ens == 3] %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = MDBZ), proj = map_proj,
                    breaks = positive_breaks(binwidth = 5)) + 
  scale_fill_gradientn(colours = rev(Redmonder::redmonder.pal(10, name = "qMSOStd")), 
                       limits = c(0, 50),
                       breaks = positive_breaks(binwidth = 5),
                       guide = guide_colorstrip()) +
  geom_mapa() +
  facet_wrap(~fisica, ncol = 5) +
  theme_minimal()
```


## Diagfiles

### Radianzas

```{r}
files <- list.files("/home/paola.corrales/datosmunin/EXP/E7/ANA/week1/", 
                    pattern = "asim.", recursive = TRUE, 
                    full.names = TRUE)
files <- files[!str_detect(files, pattern = "conv")]

diag_rad1 <- purrr::map(files, function(f) {
  read_diag_mean_rad(f) %>%
    .[press > 50 & qc == 0, .N, by = .(sensor, channel, date)] %>% 
    .[, exp := "week1"]
  
}) %>%
  rbindlist()

files <- list.files("/home/paola.corrales/datosmunin/EXP/E7/ANA/week2/", 
                    pattern = "asim.", recursive = TRUE, 
                    full.names = TRUE)
files <- files[!str_detect(files, pattern = "conv")]

diag_rad2 <- purrr::map(files, function(f) {
  read_diag_mean_rad(f) %>%
    .[press > 50 & qc == 0, .N, by = .(sensor, channel, date)] %>%
    .[, exp := "week2"] %>%
    .[]
  
}) %>%
  rbindlist()

diag_rad <- rbind(diag_rad1, diag_rad2)
# diag_rad <- read_diag_mean_rad(files)

diag_rad[date %between% c(as.Date("2018-11-11 18:00:00"), as.Date("2018-11-13 18:00:00"))] %>% 
  .[sensor %in% c("iasi_metop-a", "iasi_metop-b", "airs_aqua")] %>% 
  .[, .(count = sum(N)), by = .(sensor, date, exp)] %>% 
  ggplot(aes(date, count)) +
  geom_line(aes(color = sensor, linetype = exp)) +
  geom_point(aes(color = sensor)) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "Multiespectrales",
       subtitle = "qc == 0") +
  theme_minimal()

diag_rad[date %between% c(as.Date("2018-11-11 18:00:00"), as.Date("2018-11-13 18:00:00"))] %>% 
  .[(sensor %in% c("amsua_aqua", "ansua_metop-a", "amsua_n15", "amsua_n18"))] %>% 
  .[, .(count = sum(N)), by = .(sensor, date, exp)] %>% 
  ggplot(aes(date, count)) +
  geom_line(aes(color = sensor, linetype = exp)) +
  geom_point(aes(color = sensor)) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "AMSU - A",
       subtitle = "qc == 0") +
  theme_minimal()

diag_rad[date %between% c(as.Date("2018-11-11 18:00:00"), as.Date("2018-11-13 18:00:00"))] %>% 
  .[(sensor %in% c("hirs4_n19", "hirs4_metop-a","hirs4_metop-b"))] %>% 
  .[, .(count = sum(N)), by = .(sensor, date, exp)] %>% 
  ggplot(aes(date, count)) +
  geom_line(aes(color = sensor, linetype = exp)) +
  geom_point(aes(color = sensor)) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "HIRS 4",
       subtitle = "qc == 0") +
  theme_minimal()

diag_rad[date %between% c(as.Date("2018-11-11 18:00:00"), as.Date("2018-11-13 18:00:00"))] %>% 
  .[(sensor %in% c("mhs_metop-a", "mhs_metop-b", "mhs_n18", "mhs_n19", "mhs_metop-a"))] %>% 
  .[, .(count = sum(N)), by = .(sensor, date, exp)] %>% 
  ggplot(aes(date, count)) +
  geom_line(aes(color = sensor, linetype = exp)) +
  geom_point(aes(color = sensor)) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "MHS",
       subtitle = "qc == 0") +
  theme_minimal()

diag_rad[date %between% c(as.Date("2018-11-11 18:00:00"), as.Date("2018-11-13 18:00:00")),
         .N, by = .(date, sensor, exp)] %>% 
  ggplot(aes(date, sensor)) +
  geom_raster(aes(fill = N)) +
  scale_fill_viridis_c(trans = scales::log10_trans()) +
  facet_wrap(~exp)

```

## Convencionales

```{r}
diag1 <- read_diag_mean("/home/paola.corrales/datosmunin/EXP/E7/ANA/week1/") %>% 
  .[, exp := "week1"]

diag2 <- read_diag_mean("/home/paola.corrales/datosmunin/EXP/E7/ANA/week2/") %>% 
  .[, exp := "week2"]

diag <- rbind(diag1, diag2)
```

```{r}
diag[usage.flag == 1, .N, by = .(date, exp, var, usage.flag)] %>% 
  .[date %between% c(as.Date("2018-11-11 18:00:00"), as.Date("2018-11-13 18:00:00"))] %>% 
  # .[exp == "week2"] %>% 
  ggplot(aes(date, N)) +
  geom_point(aes(color = var, group = interaction(exp, var))) +
  geom_line(aes(color = var, linetype = exp, group = interaction(exp, var))) 
```

```{r}
seq(0, max(diag$pressure),by = 50)
cut(unique(diag$pressure), breaks = seq(0, max(diag$pressure),by = 50))

diag1 %>% 
  copy() %>% 
  .[pressure >= 1100, pressure := NA] %>%
  .[var == "q", .N, by = .(date, level = cut_width(pressure, 50, boundary = 0))] %>% 
  na.omit() %>% 
  ggplot(aes(date, fct_rev(level))) + 
  geom_raster(aes(fill = N)) +
  scale_fill_viridis_c(trans = scales::log10_trans()) +
  labs(title = "# observaciones de humedad",
       y = "intervalo de presi贸n") +
  theme_minimal()
scale_y_reverse()

diag1 %>% 
  copy() %>% 
  .[pressure >= 1100, pressure := NA] %>%
  .[var == "t", .N, by = .(date, level = cut_width(pressure, 50, boundary = 0))] %>% 
  na.omit() %>% 
  ggplot(aes(date, fct_rev(level))) + 
  geom_raster(aes(fill = N)) +
  scale_fill_viridis_c(trans = scales::log10_trans()) +
  labs(title = "# observaciones de temperatura",
       y = "intervalo de presi贸n") +
  theme_minimal()
scale_y_reverse()

```

```{r}
diag1[type %in% c(181,187) & var == "q", .N, by = .(type, date)] %>% 
  ggplot(aes(date, N)) +
  geom_line(aes(color = factor(type)))
```

