---
title: "Varianza de los errores de los coeficientes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(metR)
library(data.table)
library(lubridate)
library(scattermore)
library(patchwork)
library(unglue)
library(mesoda)

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")

geom_mapa <- function() {
  list(geom_sf(data = map, fill = NA, color = "black", size = 0.2, inherit.aes = FALSE),
       coord_sf(xlim = c(-78, -50), ylim = c(-42, -19)))
}

map_proj <- "+proj=lcc +lat_1=-30.9659996032715 +lat_2=-30.9659996032715 +lat_0=-30.9660034179688 +lon_0=-63.5670013427734 +a=6370000 +b=6370000"

satinfo <- fread("satinfo.txt") %>% 
  setnames(c("!sensor/instr/sat", "chan"), c("sensor", "channel"))

use_table <- satinfo[, c("sensor", "channel", "iuse")]

multiespectrales <- c("airs_aqua",
                      "iasi_metop-a",
                      "iasi_metop-b")
```

```{r eval=FALSE, include=FALSE}
files <- Sys.glob("/home/paola.corrales/datosmunin/EXP/prueba_BC/ANA/*/satbias_enkf/satbias_2*")


satbias <- map(files, function(f){
  print(basename(f))
  meta <- unglue::unglue(f, "/home/paola.corrales/datosmunin/EXP/prueba_BC/{exp}/{date_ana}/satbias_enkf/satbias_{date}")
  read_satbias(f) %>% 
    as.data.table() %>% 
    .[, ":="(date = ymd_hms(meta[[1]][["date"]]),
             exp = meta[[1]][["exp"]])] 
  
}) %>% 
  rbindlist()

sensores <- c("amsua_n15",
              "amsua_n18",
              "amsua_n19",
              # "amsua_metop_a",
              "amsua_metop-b",
              "amsua_aqua",
              "airs_aqua",
              "iasi_metop-a",
              "iasi_metop-b", 
              "hirs4_n19",
              "hirs4_metop-a",
              "hirs4_metop-b",
              "mhs_metop-a",
              "mhs_metop-b",
              "mhs_n18",
              "mhs_n19",
              "mhs_metop-a",
              "atms_npp",
              "atms_n20",
              "cris-fsr_npp",
              "cris-fsr_n20"
)

satbias <- satbias[sensor %in% sensores]

satinfo <- fread("satinfo.txt") %>% 
  setnames(c("!sensor/instr/sat", "chan"), c("sensor", "channel"))

satbias <- satinfo[satbias, on = c("sensor", "channel")]

multiespectrales <- c("airs_aqua",
                      "iasi_metop-a",
                      "iasi_metop-b")

this_sensor <- sensores[2]


for (this_sensor in sensores){
  print(this_sensor)
  g <- satbias[sensor %in% this_sensor & iuse == 1] %>% 
    melt(measure.vars = paste0("coeff", c(1, 3:5, 8))) %>% 
    ggplot(aes(date, value)) +
    # geom_point(aes(color = variable), size= 0.5) +
    geom_path(aes(color = variable), size= 0.5) +
    scale_color_brewer(type = "qual", palette = "Dark2",
                       labels = c("coeff1" = "Offset",
                                  "coeff3" = "CLW",
                                  "coeff4" = "TLR^2",
                                  "coeff5" = "TLR",
                                  "coeff8" = "Emiss")) +
    scale_x_datetime(date_labels = "%d") +
    labs(title = paste("Coefficientes for", this_sensor),
         color = "") +
    facet_wrap(~channel, scales = "free_y", ncol = 5) +
    theme_minimal() +
    theme(legend.position = "bottom")
  
  rows <- satbias[sensor %in% this_sensor & iuse == 1, channel] %>% 
    unique(by = channel) %>% 
    length() / 5
  
  h <- ceiling(ceiling(rows)*700/300)
  if (h > 0){
    
    ggsave(paste0(this_sensor, ".png"), plot = g, width = 9, height = h, limitsize = FALSE)
  }
}
```



```{r}
files <- Sys.glob("/home/paola.corrales/datosmunin/EXP/prueba_BC/ANA/*/diagfiles/asim*")

files <- files[!str_detect(files, pattern = "conv")]

diag_rad <- purrr::map(files, function(f) {
  
  out <- mesoda::read_diag_rad(f, exp = "training") %>%
    use_table[., on = c("sensor", "channel")] %>% 
    .[, usage.flag := fifelse(errinv %between% c(0.0000316227, 1000) & 
                                iuse == 1 &
                                qc == 0 & 
                                peakwt %between% c(0.001, 1200), 1, -1)]
}) %>% 
  rbindlist()

# 
# diag_rad[, .(tbc_mean = mean(tbc, na.rm = TRUE),
#              tbcnob_mean = mean(tbcnob, na.rm = TRUE),
#              count = .N),
#          by = .(sensor, channel, usage.flag, date)] %>%
#   fwrite("/home/paola.corrales/mesoda/analysis/data/derived_data/bias_res_ori.csv")


```

```{r eval=FALSE, include=FALSE}
coef_zero <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_zero-init.rds")$est %>% 
  .[, .(tbc_mean = mean(OmB_BC, na.rm = TRUE),
        tbcnob_mean = mean(OmB, na.rm = TRUE),
        tbc_sd = sd(OmB_BC, na.rm = TRUE),
        tbcnob_sd = sd(OmB, na.rm = TRUE),
        count = .N),
    by = .(sensor, channel)] %>% 
  #use_table[., on = c("sensor", "channel")] %>% 
  # .[iuse == 1] %>% 
  .[, ":="(run = "zero",
           iuse = NULL)] 

coef_gfs <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_gfs-init.rds")$est %>%
  .[, .(tbc_mean = mean(OmB_BC, na.rm = TRUE),
        tbcnob_mean = mean(OmB, na.rm = TRUE),
        tbc_sd = sd(OmB_BC, na.rm = TRUE),
        tbcnob_sd = sd(OmB, na.rm = TRUE),
        count = .N),
    by = .(sensor, channel)] %>% 
  #use_table[., on = c("sensor", "channel")] %>% 
  # .[iuse == 1] %>% 
  .[, ":="(run = "gfs",
           iuse = NULL)] 

coef_training <- diag_rad %>% #fread("/home/paola.corrales/mesoda/analysis/data/derived_data/bias_res_ori.csv") %>% 
  .[qc == 0] %>% 
  .[, usage.flag := NULL] %>%
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_sd = sd(tbc, na.rm = TRUE),
        tbcnob_sd = sd(tbcnob, na.rm = TRUE),
        count = .N),
    by = .(sensor, channel)] %>%
  .[, run := "training"] 

sensor_list <- unique(coef_training$sensor)


  rbind(coef_zero, coef_gfs, coef_training) %>% 
    .[sensor == "iasi_metop-b"] %>% 
    melt(id.vars = c("sensor", "channel", "run"), 
         measure.vars = c("tbcnob_mean", "tbc_mean", "tbc_sd", "tbcnob_sd")) %>% 
    separate(variable, into = c("variable", "estadistico")) %>% 
    dcast(sensor + channel + run + variable ~ estadistico, value.var = "value") %>% 
    use_table[., on = c("sensor", "channel")] %>%
    ggplot(aes(channel, mean)) +
    geom_hline(yintercept = 0, color = "grey20") +
    # geom_errorbar(data = ~.x[run == "training" & variable == "tbcnob"], 
    #               aes(ymin = mean - sd, ymax = mean + sd, fill = "no BC"), width = 0.15) +
    geom_point(data = ~.x[run == "training" & variable == "tbcnob"], aes(fill = "no BC"), size = 2, shape = 15) +
    # geom_errorbar(data = ~.x[variable == "tbc"], aes(ymin = mean - sd, ymax = mean + sd, color = run), 
    #               width = 0.15, alpha = 0.8) +
    geom_point(data = ~.x[variable == "tbc"], aes(color = run), alpha = 0.8) +
    scale_color_viridis_d(labels = c("From GFS", "From Zero", "From GSI")) +
    facet_wrap(~iuse, scales = "free_y") +
    labs(x = "Channel", y = "Mean BIAS", color = NULL, fill = NULL,
         caption = "iasi_metop-b") +
    theme_minimal()

pd <- position_dodge(width = 0.4)
for (s in sensor_list) {
  rbind(coef_zero, coef_gfs, coef_training) %>% 
    .[sensor == s & abs(tbc_mean) < 10] %>% 
    melt(id.vars = c("sensor", "channel", "run"), 
         measure.vars = c("tbcnob_mean", "tbc_mean", "tbc_sd", "tbcnob_sd")) %>% 
    separate(variable, into = c("variable", "estadistico")) %>% 
    dcast(sensor + channel + run + variable ~ estadistico, value.var = "value") %>% 
    ggplot(aes(channel, mean)) +
    geom_hline(yintercept = 0, color = "grey20") +
    geom_errorbar(data = ~.x[run == "training" & variable == "tbcnob"], 
                  aes(ymin = mean - sd, ymax = mean + sd, fill = "no BC"), width = 0.15, position = pd) +
    geom_point(data = ~.x[run == "training" & variable == "tbcnob"], aes(fill = "no BC"), 
               size = 2, shape = 15, position = pd) +
    geom_errorbar(data = ~.x[variable == "tbc"], aes(ymin = mean - sd, ymax = mean + sd, color = run), 
                  width = 0.15, alpha = 0.8, position = pd) +
    geom_point(data = ~.x[variable == "tbc"], aes(color = run), alpha = 0.8, position = pd) +
    scale_color_viridis_d(labels = c("From GFS", "From Zero", "From GSI")) +
    labs(x = "Channel", y = "Mean BIAS", color = NULL, fill = NULL,
         caption = paste0(s)) +
    theme_minimal()
  
  ggsave(paste0("/home/paola.corrales/campos/mean_sd_bias_", s, ".png"), width = 10, height = 6)
}
```

```{r}
coeff_gfs <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_gfs-init.rds")$coef_out 

bias_res_gfs <- diag_rad[qc == 0, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", paste0("pred", 1:12), "date")] %>% 
  coeff_gfs[., on = c("sensor", "channel")] %>% 
  .[, bc := coeff1*pred1 + coeff2*pred2 +
      coeff3*pred3 + coeff4*pred4 +
      coeff5*pred5 + coeff6*pred6 +
      coeff7*pred7 + coeff8*pred8 +
      coeff9*pred9 + coeff10*pred10 +
      coeff11*pred11 + coeff12*pred12] %>% 
  .[, tbc_gfs := tbcnob - bc] %>% 
  .[, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", "date", "bc", "tbc_gfs")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_") %>% 
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_test_mean = mean(tbc_gfs, na.rm = TRUE)),
    by = .(sensor, channel, date)] %>% 
  .[, run := "gfs"]


coeff_zero <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_zero-init.rds")$coef_out

bias_res_zero <- diag_rad[qc == 0, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", paste0("pred", 1:12), "date")] %>% 
  coeff_zero[., on = c("sensor", "channel")] %>% 
  .[, bc := coeff1*pred1 + coeff2*pred2 +
      coeff3*pred3 + coeff4*pred4 +
      coeff5*pred5 + coeff6*pred6 +
      coeff7*pred7 + coeff8*pred8 +
      coeff9*pred9 + coeff10*pred10 +
      coeff11*pred11 + coeff12*pred12] %>% 
  .[, tbc_zero := tbcnob - bc] %>% 
  .[, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", "date", "bc", "tbc_zero")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_") %>% 
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_test_mean = mean(tbc_zero, na.rm = TRUE)),
    by = .(sensor, channel, date)] %>% 
  .[, run := "zero"]

bias_res <- rbind(bias_res_zero, bias_res_gfs)

# fwrite(.Last.value, "/home/paola.corrales/mesoda/analysis/data/derived_data/bc_gfs.csv")

bias_res %>% 
  melt(id.vars = c("sensor", "channel", "date", "run")) %>% 
  ggplot(aes(sensor, value)) +
  geom_hline(yintercept = 0, color = "grey20") +
  geom_boxplot(aes(color = variable)) +
  scale_color_brewer(palette = "Dark2", labels = c("From GSI", "no BC", "Off-line")) +
  facet_grid(run~., scales = "free") +
  labs(x = NULL, y = "Mean BIAS", color = NULL,
       caption = "QC == 0") +
  theme_minimal()


bias_res %>% 
  melt(id.vars = c("sensor", "channel", "date", "run")) %>% 
  .[abs(value) < 10] %>% 
  ggplot(aes(sensor, value)) +
  geom_hline(yintercept = 0, color = "grey20") +
  geom_boxplot(aes(color = variable)) +
  scale_color_brewer(palette = "Dark2", labels = c("From GSI", "no BC", "Off-line")) +
  facet_grid(run~., scales = "free") +
  labs(x = NULL, y = "Mean BIAS", color = NULL,
       caption = "QC == 0 & abs(BIAS)<10") +
  theme_minimal()

```
```{r}

# coeff_gfs <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_gfs-init.rds")$coef_out 

bias_res_gfs <- diag_rad[usage.flag == 1, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", paste0("pred", 1:12), "date")] %>% 
  coeff_gfs[., on = c("sensor", "channel")] %>% 
  .[, bc := coeff1*pred1 + coeff2*pred2 +
      coeff3*pred3 + coeff4*pred4 +
      coeff5*pred5 + coeff6*pred6 +
      coeff7*pred7 + coeff8*pred8 +
      coeff9*pred9 + coeff10*pred10 +
      coeff11*pred11 + coeff12*pred12] %>% 
  .[, tbc_gfs := tbcnob - bc] %>% 
  .[, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", "date", "bc", "tbc_gfs")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_") %>% 
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_test_mean = mean(tbc_gfs, na.rm = TRUE)),
    by = .(sensor, channel, date)] %>% 
  .[, run := "gfs"]


# coeff_zero <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_zero-init.rds")$coef_out

bias_res_zero <- diag_rad[usage.flag == 1, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", paste0("pred", 1:12), "date")] %>% 
  coeff_zero[., on = c("sensor", "channel")] %>% 
  .[, bc := coeff1*pred1 + coeff2*pred2 +
      coeff3*pred3 + coeff4*pred4 +
      coeff5*pred5 + coeff6*pred6 +
      coeff7*pred7 + coeff8*pred8 +
      coeff9*pred9 + coeff10*pred10 +
      coeff11*pred11 + coeff12*pred12] %>% 
  .[, tbc_zero := tbcnob - bc] %>% 
  .[, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", "date", "bc", "tbc_zero")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_") %>% 
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_test_mean = mean(tbc_zero, na.rm = TRUE)),
    by = .(sensor, channel, date)] %>% 
  .[, run := "zero"]

bias_res <- rbind(bias_res_zero, bias_res_gfs)

# fwrite(.Last.value, "/home/paola.corrales/mesoda/analysis/data/derived_data/bc_gfs.csv")

bias_res %>% 
  melt(id.vars = c("sensor", "channel", "date", "run")) %>% 
  ggplot(aes(sensor, value)) +
  geom_hline(yintercept = 0, color = "grey20") +
  geom_boxplot(aes(color = variable)) +
  scale_color_brewer(palette = "Dark2", labels = c("From GSI", "no BC", "Off-line")) +
  facet_grid(run~., scales = "free") +
  labs(x = NULL, y = "Mean BIAS", color = NULL,
       caption = "iuse == 1") +
  theme_minimal()


bias_res %>% 
  melt(id.vars = c("sensor", "channel", "date", "run")) %>% 
  .[abs(value) < 10] %>% 
  ggplot(aes(sensor, value)) +
  geom_hline(yintercept = 0, color = "grey20") +
  geom_boxplot(aes(color = variable)) +
  scale_color_brewer(palette = "Dark2", labels = c("From GSI", "no BC", "Off-line")) +
  facet_grid(run~., scales = "free") +
  labs(x = NULL, y = "Mean BIAS", color = NULL,
       caption = "iuse == 1 & abs(BIAS)<10") +
  theme_minimal()

```

```{r}
# coeff_gfs <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_gfs-init.rds")$coef_out 

bias_res_gfs <- diag_rad[usage.flag == 1, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", paste0("pred", 1:12), "date")] %>% 
  coeff_gfs[., on = c("sensor", "id" = "channel")] %>% 
  .[, bc := coeff1*pred1 + coeff2*pred2 +
      coeff3*pred3 + coeff4*pred4 +
      coeff5*pred5 + coeff6*pred6 +
      coeff7*pred7 + coeff8*pred8 +
      coeff9*pred9 + coeff10*pred10 +
      coeff11*pred11 + coeff12*pred12] %>% 
  .[, tbc_gfs := tbcnob - bc] %>% 
  .[, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", "date", "bc", "tbc_gfs")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_") %>% 
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_test_mean = mean(tbc_gfs, na.rm = TRUE)),
    by = .(sensor, channel, date)] %>% 
  .[, run := "gfs"]


# coeff_zero <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/satbias_trained_zero-init.rds")$coef_out

bias_res_zero <- diag_rad[usage.flag == 1, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", paste0("pred", 1:12), "date")] %>% 
  coeff_zero[., on = c("sensor", "id" = "channel")] %>% 
  .[, bc := coeff1*pred1 + coeff2*pred2 +
      coeff3*pred3 + coeff4*pred4 +
      coeff5*pred5 + coeff6*pred6 +
      coeff7*pred7 + coeff8*pred8 +
      coeff9*pred9 + coeff10*pred10 +
      coeff11*pred11 + coeff12*pred12] %>% 
  .[, tbc_zero := tbcnob - bc] %>% 
  .[, c("sensor", "channel", "iuse", "tb_obs", "tbc", "tbcnob", "date", "bc", "tbc_zero")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_") %>% 
  .[, .(tbc_mean = mean(tbc, na.rm = TRUE),
        tbcnob_mean = mean(tbcnob, na.rm = TRUE),
        tbc_test_mean = mean(tbc_zero, na.rm = TRUE)),
    by = .(sensor, channel, date)] %>% 
  .[, run := "zero"]

bias_res <- rbind(bias_res_zero, bias_res_gfs)


```


```{r}

files <- c(Sys.glob("/home/paola.corrales/datosmunin/EXP/prueba_BC/test/20181121020000*/diagfiles/asim_iasi*ensmean"))


rad <- purrr::map(files, function(f) {
  meta <- unglue(f, "/home/paola.corrales/datosmunin/EXP/prueba_BC/test/20181121020000_{test}/diagfiles/asim_iasi_metop-b_20181121020000.ensmean")
  rad <- read_diag_rad(f, "E7") %>% 
    .[, test := meta[[1]][["test"]]] %>% 
    .[, wavenumber := 1/(299792458/(freq*10000000))] %>% 
    # .[wavenumber %between% c(1367, 1422.25)] %>% 
    satinfo[., on = c("sensor", "channel")]
}) %>% rbindlist()

rad %>% 
  .[sensor == "iasi_metop-b" & 
      channel == 3049 &
      # channel %between% c(3000, 3100) &
      errinv %between% c(0.0000316227, 1000) & 
      qc == 0 & 
      iuse == 1 &
      peakwt %between% c(0.001, 1200)] %>% 
  .[, date := factor(date)] %>% 
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_point(aes(color = tbc)) +
  scale_color_divergent(trans = mesoda::symlog_trans(),
                        guide = guide_colourbar(barheight = 15, barwidth = 1)) +
  geom_mapa() +
  facet_wrap(channel~test) +
  labs(x = NULL, y = NULL, color = NULL) +
  theme_minimal() 


rad[errinv %between% c(0.0000316227, 1000) & 
      qc == 0 & 
      iuse == 1 &
      peakwt %between% c(0.001, 1200), .N, by = .(channel, test)] %>% 
  ggplot(aes(factor(channel), test)) +
  geom_tile(aes(fill = N)) +
  scale_fill_viridis_c() +
  labs(x = "Channel", y = NULL) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90),
        aspect.ratio = 1/4)

rad[errinv %between% c(0.0000316227, 1000) & 
      qc == 0 & 
      iuse == 1 &
      peakwt %between% c(0.001, 1200), .N, by = .(test)] 


```
















